services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # persistance des données
      # - ./init-db:/docker-entrypoint-initdb.d:ro   # scripts d'initialisation
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - metanet1

  cube:
    image: cubejs/cube:latest
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: ${POSTGRES_DB}
      CUBEJS_DB_USER: ${POSTGRES_USER}
      CUBEJS_DB_PASS: ${POSTGRES_PASSWORD}
      CUBEJS_API_SECRET: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
      CUBEJS_DEV_MODE: "true"
    ports:
      - "4000:4000"
    depends_on:
        postgres:
          condition: service_healthy
    networks:
    - metanet1
    volumes:
      - ./cube/model:/cube/conf/model

  metabase:
    image: metabase/metabase:latest
    volumes:
      - /dev/urandom:/dev/random:ro
      # - ./plugins/:/plugins/          # pour le driver JDBC Cube.js
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    networks:
      - metanet1
    # healthcheck:
    #   test: curl --fail -I http://localhost:3000/api/health || exit 1
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      # - cube

volumes:
  postgres_data:

networks:
  metanet1: